/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "api_options.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ApiVoid, ApiVoid, AUTO)


/* Definition for extension field needs_setup_connection */
typedef struct _needs_setup_connection_extmsg {
    bool needs_setup_connection;
} needs_setup_connection_extmsg;
#define needs_setup_connection_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     needs_setup_connection, 1038)
#define needs_setup_connection_extmsg_CALLBACK NULL
#define needs_setup_connection_extmsg_DEFAULT NULL
pb_byte_t needs_setup_connection_extmsg_default[] = {0x00};
PB_BIND(needs_setup_connection_extmsg, needs_setup_connection_extmsg, 4)
const pb_extension_type_t needs_setup_connection = {
    NULL,
    NULL,
    &needs_setup_connection_extmsg_msg
};

/* Definition for extension field needs_authentication */
typedef struct _needs_authentication_extmsg {
    bool needs_authentication;
} needs_authentication_extmsg;
#define needs_authentication_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     needs_authentication, 1039)
#define needs_authentication_extmsg_CALLBACK NULL
#define needs_authentication_extmsg_DEFAULT NULL
pb_byte_t needs_authentication_extmsg_default[] = {0x00};
PB_BIND(needs_authentication_extmsg, needs_authentication_extmsg, 4)
const pb_extension_type_t needs_authentication = {
    NULL,
    NULL,
    &needs_authentication_extmsg_msg
};

/* Definition for extension field id */
typedef struct _id_extmsg {
    uint32_t id;
} id_extmsg;
#define id_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   id,              1036)
#define id_extmsg_CALLBACK NULL
#define id_extmsg_DEFAULT NULL
pb_byte_t id_extmsg_default[] = {0x00};
PB_BIND(id_extmsg, id_extmsg, 4)
const pb_extension_type_t id = {
    NULL,
    NULL,
    &id_extmsg_msg
};

/* Definition for extension field source */
typedef struct _source_extmsg {
    APISourceType source;
} source_extmsg;
#define source_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, ENUM,     source,          1037)
#define source_extmsg_CALLBACK NULL
#define source_extmsg_DEFAULT NULL
pb_byte_t source_extmsg_default[] = {0x00};
PB_BIND(source_extmsg, source_extmsg, 4)
const pb_extension_type_t source = {
    NULL,
    NULL,
    &source_extmsg_msg
};

/* Definition for extension field ifdef */
typedef struct _ifdef_extmsg {
    pb_callback_t ifdef;
} ifdef_extmsg;
#define ifdef_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   ifdef,           1038)
#define ifdef_extmsg_CALLBACK pb_default_field_callback
#define ifdef_extmsg_DEFAULT NULL
pb_byte_t ifdef_extmsg_default[] = {0x00};
PB_BIND(ifdef_extmsg, ifdef_extmsg, 4)
const pb_extension_type_t ifdef = {
    NULL,
    NULL,
    &ifdef_extmsg_msg
};

/* Definition for extension field ApiLog */
typedef struct _ApiLog_extmsg {
    bool ApiLog;
} ApiLog_extmsg;
#define ApiLog_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     ApiLog,          1039)
#define ApiLog_extmsg_CALLBACK NULL
#define ApiLog_extmsg_DEFAULT NULL
pb_byte_t ApiLog_extmsg_default[] = {0x00};
PB_BIND(ApiLog_extmsg, ApiLog_extmsg, 4)
const pb_extension_type_t ApiLog = {
    NULL,
    NULL,
    &ApiLog_extmsg_msg
};

/* Definition for extension field no_delay */
typedef struct _no_delay_extmsg {
    bool no_delay;
} no_delay_extmsg;
#define no_delay_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     no_delay,        1040)
#define no_delay_extmsg_CALLBACK NULL
#define no_delay_extmsg_DEFAULT NULL
pb_byte_t no_delay_extmsg_default[] = {0x00};
PB_BIND(no_delay_extmsg, no_delay_extmsg, 4)
const pb_extension_type_t no_delay = {
    NULL,
    NULL,
    &no_delay_extmsg_msg
};

/* Definition for extension field base_class */
typedef struct _base_class_extmsg {
    pb_callback_t base_class;
} base_class_extmsg;
#define base_class_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   base_class,      1041)
#define base_class_extmsg_CALLBACK pb_default_field_callback
#define base_class_extmsg_DEFAULT NULL
pb_byte_t base_class_extmsg_default[] = {0x00};
PB_BIND(base_class_extmsg, base_class_extmsg, 4)
const pb_extension_type_t base_class = {
    NULL,
    NULL,
    &base_class_extmsg_msg
};

/* Definition for extension field inline_encode */
typedef struct _inline_encode_extmsg {
    bool inline_encode;
} inline_encode_extmsg;
#define inline_encode_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     inline_encode,   1042)
#define inline_encode_extmsg_CALLBACK NULL
#define inline_encode_extmsg_DEFAULT NULL
pb_byte_t inline_encode_extmsg_default[] = {0x00};
PB_BIND(inline_encode_extmsg, inline_encode_extmsg, 4)
const pb_extension_type_t inline_encode = {
    NULL,
    NULL,
    &inline_encode_extmsg_msg
};

/* Definition for extension field speed_optimized */
typedef struct _speed_optimized_extmsg {
    bool speed_optimized;
} speed_optimized_extmsg;
#define speed_optimized_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     speed_optimized, 1043)
#define speed_optimized_extmsg_CALLBACK NULL
#define speed_optimized_extmsg_DEFAULT NULL
pb_byte_t speed_optimized_extmsg_default[] = {0x00};
PB_BIND(speed_optimized_extmsg, speed_optimized_extmsg, 4)
const pb_extension_type_t speed_optimized = {
    NULL,
    NULL,
    &speed_optimized_extmsg_msg
};

/* Definition for extension field field_ifdef */
typedef struct _field_ifdef_extmsg {
    pb_callback_t field_ifdef;
} field_ifdef_extmsg;
#define field_ifdef_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   field_ifdef,     1042)
#define field_ifdef_extmsg_CALLBACK pb_default_field_callback
#define field_ifdef_extmsg_DEFAULT NULL
pb_byte_t field_ifdef_extmsg_default[] = {0x00};
PB_BIND(field_ifdef_extmsg, field_ifdef_extmsg, 4)
const pb_extension_type_t field_ifdef = {
    NULL,
    NULL,
    &field_ifdef_extmsg_msg
};

/* Definition for extension field fixed_array_size */
typedef struct _fixed_array_size_extmsg {
    uint32_t fixed_array_size;
} fixed_array_size_extmsg;
#define fixed_array_size_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   fixed_array_size, 50007)
#define fixed_array_size_extmsg_CALLBACK NULL
#define fixed_array_size_extmsg_DEFAULT NULL
pb_byte_t fixed_array_size_extmsg_default[] = {0x00};
PB_BIND(fixed_array_size_extmsg, fixed_array_size_extmsg, 4)
const pb_extension_type_t fixed_array_size = {
    NULL,
    NULL,
    &fixed_array_size_extmsg_msg
};

/* Definition for extension field fixed_array_skip_zero */
typedef struct _fixed_array_skip_zero_extmsg {
    bool fixed_array_skip_zero;
} fixed_array_skip_zero_extmsg;
#define fixed_array_skip_zero_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     fixed_array_skip_zero, 50009)
#define fixed_array_skip_zero_extmsg_CALLBACK NULL
#define fixed_array_skip_zero_extmsg_DEFAULT NULL
pb_byte_t fixed_array_skip_zero_extmsg_default[] = {0x00};
PB_BIND(fixed_array_skip_zero_extmsg, fixed_array_skip_zero_extmsg, 4)
const pb_extension_type_t fixed_array_skip_zero = {
    NULL,
    NULL,
    &fixed_array_skip_zero_extmsg_msg
};

/* Definition for extension field fixed_array_size_define */
typedef struct _fixed_array_size_define_extmsg {
    pb_callback_t fixed_array_size_define;
} fixed_array_size_define_extmsg;
#define fixed_array_size_define_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   fixed_array_size_define, 50010)
#define fixed_array_size_define_extmsg_CALLBACK pb_default_field_callback
#define fixed_array_size_define_extmsg_DEFAULT NULL
pb_byte_t fixed_array_size_define_extmsg_default[] = {0x00};
PB_BIND(fixed_array_size_define_extmsg, fixed_array_size_define_extmsg, 4)
const pb_extension_type_t fixed_array_size_define = {
    NULL,
    NULL,
    &fixed_array_size_define_extmsg_msg
};

/* Definition for extension field fixed_array_with_length_define */
typedef struct _fixed_array_with_length_define_extmsg {
    pb_callback_t fixed_array_with_length_define;
} fixed_array_with_length_define_extmsg;
#define fixed_array_with_length_define_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   fixed_array_with_length_define, 50011)
#define fixed_array_with_length_define_extmsg_CALLBACK pb_default_field_callback
#define fixed_array_with_length_define_extmsg_DEFAULT NULL
pb_byte_t fixed_array_with_length_define_extmsg_default[] = {0x00};
PB_BIND(fixed_array_with_length_define_extmsg, fixed_array_with_length_define_extmsg, 4)
const pb_extension_type_t fixed_array_with_length_define = {
    NULL,
    NULL,
    &fixed_array_with_length_define_extmsg_msg
};

/* Definition for extension field pointer_to_buffer */
typedef struct _pointer_to_buffer_extmsg {
    bool pointer_to_buffer;
} pointer_to_buffer_extmsg;
#define pointer_to_buffer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     pointer_to_buffer, 50012)
#define pointer_to_buffer_extmsg_CALLBACK NULL
#define pointer_to_buffer_extmsg_DEFAULT NULL
pb_byte_t pointer_to_buffer_extmsg_default[] = {0x00};
PB_BIND(pointer_to_buffer_extmsg, pointer_to_buffer_extmsg, 4)
const pb_extension_type_t pointer_to_buffer = {
    NULL,
    NULL,
    &pointer_to_buffer_extmsg_msg
};

/* Definition for extension field container_pointer */
typedef struct _container_pointer_extmsg {
    pb_callback_t container_pointer;
} container_pointer_extmsg;
#define container_pointer_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   container_pointer, 50001)
#define container_pointer_extmsg_CALLBACK pb_default_field_callback
#define container_pointer_extmsg_DEFAULT NULL
pb_byte_t container_pointer_extmsg_default[] = {0x00};
PB_BIND(container_pointer_extmsg, container_pointer_extmsg, 4)
const pb_extension_type_t container_pointer = {
    NULL,
    NULL,
    &container_pointer_extmsg_msg
};

/* Definition for extension field fixed_vector */
typedef struct _fixed_vector_extmsg {
    bool fixed_vector;
} fixed_vector_extmsg;
#define fixed_vector_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     fixed_vector,    50013)
#define fixed_vector_extmsg_CALLBACK NULL
#define fixed_vector_extmsg_DEFAULT NULL
pb_byte_t fixed_vector_extmsg_default[] = {0x00};
PB_BIND(fixed_vector_extmsg, fixed_vector_extmsg, 4)
const pb_extension_type_t fixed_vector = {
    NULL,
    NULL,
    &fixed_vector_extmsg_msg
};

/* Definition for extension field container_pointer_no_template */
typedef struct _container_pointer_no_template_extmsg {
    pb_callback_t container_pointer_no_template;
} container_pointer_no_template_extmsg;
#define container_pointer_no_template_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   container_pointer_no_template, 50014)
#define container_pointer_no_template_extmsg_CALLBACK pb_default_field_callback
#define container_pointer_no_template_extmsg_DEFAULT NULL
pb_byte_t container_pointer_no_template_extmsg_default[] = {0x00};
PB_BIND(container_pointer_no_template_extmsg, container_pointer_no_template_extmsg, 4)
const pb_extension_type_t container_pointer_no_template = {
    NULL,
    NULL,
    &container_pointer_no_template_extmsg_msg
};

/* Definition for extension field packed_buffer */
typedef struct _packed_buffer_extmsg {
    bool packed_buffer;
} packed_buffer_extmsg;
#define packed_buffer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     packed_buffer,   50015)
#define packed_buffer_extmsg_CALLBACK NULL
#define packed_buffer_extmsg_DEFAULT NULL
pb_byte_t packed_buffer_extmsg_default[] = {0x00};
PB_BIND(packed_buffer_extmsg, packed_buffer_extmsg, 4)
const pb_extension_type_t packed_buffer = {
    NULL,
    NULL,
    &packed_buffer_extmsg_msg
};

/* Definition for extension field force */
typedef struct _force_extmsg {
    bool force;
} force_extmsg;
#define force_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     force,           50016)
#define force_extmsg_CALLBACK NULL
#define force_extmsg_DEFAULT NULL
pb_byte_t force_extmsg_default[] = {0x00};
PB_BIND(force_extmsg, force_extmsg, 4)
const pb_extension_type_t force = {
    NULL,
    NULL,
    &force_extmsg_msg
};

/* Definition for extension field max_value */
typedef struct _max_value_extmsg {
    uint32_t max_value;
} max_value_extmsg;
#define max_value_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   max_value,       50017)
#define max_value_extmsg_CALLBACK NULL
#define max_value_extmsg_DEFAULT NULL
pb_byte_t max_value_extmsg_default[] = {0x00};
PB_BIND(max_value_extmsg, max_value_extmsg, 4)
const pb_extension_type_t max_value = {
    NULL,
    NULL,
    &max_value_extmsg_msg
};

/* Definition for extension field max_data_length */
typedef struct _max_data_length_extmsg {
    uint32_t max_data_length;
} max_data_length_extmsg;
#define max_data_length_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   max_data_length, 50018)
#define max_data_length_extmsg_CALLBACK NULL
#define max_data_length_extmsg_DEFAULT NULL
pb_byte_t max_data_length_extmsg_default[] = {0x00};
PB_BIND(max_data_length_extmsg, max_data_length_extmsg, 4)
const pb_extension_type_t max_data_length = {
    NULL,
    NULL,
    &max_data_length_extmsg_msg
};

/* Definition for extension field mac_address */
typedef struct _mac_address_extmsg {
    bool mac_address;
} mac_address_extmsg;
#define mac_address_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     mac_address,     50019)
#define mac_address_extmsg_CALLBACK NULL
#define mac_address_extmsg_DEFAULT NULL
pb_byte_t mac_address_extmsg_default[] = {0x00};
PB_BIND(mac_address_extmsg, mac_address_extmsg, 4)
const pb_extension_type_t mac_address = {
    NULL,
    NULL,
    &mac_address_extmsg_msg
};




