/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_API_OPTIONS_PB_H_INCLUDED
#define PB_API_OPTIONS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _APISourceType {
    APISourceType_SOURCE_BOTH = 0,
    APISourceType_SOURCE_SERVER = 1,
    APISourceType_SOURCE_CLIENT = 2
} APISourceType;

/* Struct definitions */
typedef struct _ApiVoid {
    char dummy_field;
} ApiVoid;


/* Extensions */
extern const pb_extension_type_t needs_setup_connection; /* field type: bool needs_setup_connection; */
extern const pb_extension_type_t needs_authentication; /* field type: bool needs_authentication; */
extern const pb_extension_type_t id; /* field type: uint32_t id; */
extern const pb_extension_type_t source; /* field type: APISourceType source; */
extern const pb_extension_type_t ifdef; /* field type: pb_callback_t ifdef; */
extern const pb_extension_type_t ApiLog; /* field type: bool ApiLog; */
extern const pb_extension_type_t no_delay; /* field type: bool no_delay; */
extern const pb_extension_type_t base_class; /* field type: pb_callback_t base_class; */
extern const pb_extension_type_t inline_encode; /* field type: bool inline_encode; */
extern const pb_extension_type_t speed_optimized; /* field type: bool speed_optimized; */
extern const pb_extension_type_t field_ifdef; /* field type: pb_callback_t field_ifdef; */
extern const pb_extension_type_t fixed_array_size; /* field type: uint32_t fixed_array_size; */
extern const pb_extension_type_t fixed_array_skip_zero; /* field type: bool fixed_array_skip_zero; */
extern const pb_extension_type_t fixed_array_size_define; /* field type: pb_callback_t fixed_array_size_define; */
extern const pb_extension_type_t fixed_array_with_length_define; /* field type: pb_callback_t fixed_array_with_length_define; */
extern const pb_extension_type_t pointer_to_buffer; /* field type: bool pointer_to_buffer; */
extern const pb_extension_type_t container_pointer; /* field type: pb_callback_t container_pointer; */
extern const pb_extension_type_t fixed_vector; /* field type: bool fixed_vector; */
extern const pb_extension_type_t container_pointer_no_template; /* field type: pb_callback_t container_pointer_no_template; */
extern const pb_extension_type_t packed_buffer; /* field type: bool packed_buffer; */
extern const pb_extension_type_t force; /* field type: bool force; */
extern const pb_extension_type_t max_value; /* field type: uint32_t max_value; */
extern const pb_extension_type_t max_data_length; /* field type: uint32_t max_data_length; */
extern const pb_extension_type_t mac_address; /* field type: bool mac_address; */

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _APISourceType_MIN APISourceType_SOURCE_BOTH
#define _APISourceType_MAX APISourceType_SOURCE_CLIENT
#define _APISourceType_ARRAYSIZE ((APISourceType)(APISourceType_SOURCE_CLIENT+1))



/* Initializer values for message structs */
#define ApiVoid_init_default                     {0}
#define ApiVoid_init_zero                        {0}

/* Field tags (for use in manual encoding/decoding) */
#define needs_setup_connection_tag               1038
#define needs_authentication_tag                 1039
#define id_tag                                   1036
#define source_tag                               1037
#define ifdef_tag                                1038
#define ApiLog_tag                               1039
#define no_delay_tag                             1040
#define base_class_tag                           1041
#define inline_encode_tag                        1042
#define speed_optimized_tag                      1043
#define field_ifdef_tag                          1042
#define fixed_array_size_tag                     50007
#define fixed_array_skip_zero_tag                50009
#define fixed_array_size_define_tag              50010
#define fixed_array_with_length_define_tag       50011
#define pointer_to_buffer_tag                    50012
#define container_pointer_tag                    50001
#define fixed_vector_tag                         50013
#define container_pointer_no_template_tag        50014
#define packed_buffer_tag                        50015
#define force_tag                                50016
#define max_value_tag                            50017
#define max_data_length_tag                      50018
#define mac_address_tag                          50019

/* Struct field encoding specification for nanopb */
#define ApiVoid_FIELDLIST(X, a) \

#define ApiVoid_CALLBACK NULL
#define ApiVoid_DEFAULT NULL

extern const pb_msgdesc_t ApiVoid_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ApiVoid_fields &ApiVoid_msg

/* Maximum encoded size of messages (where known) */
#define API_OPTIONS_PB_H_MAX_SIZE                ApiVoid_size
#define ApiVoid_size                             0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
