/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "esphome_api.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(esphome_api_HelloRequest, esphome_api_HelloRequest, AUTO)


PB_BIND(esphome_api_HelloResponse, esphome_api_HelloResponse, AUTO)


PB_BIND(esphome_api_ConnectRequest, esphome_api_ConnectRequest, AUTO)


PB_BIND(esphome_api_ConnectResponse, esphome_api_ConnectResponse, AUTO)


PB_BIND(esphome_api_DeviceInfoRequest, esphome_api_DeviceInfoRequest, AUTO)


PB_BIND(esphome_api_DeviceInfoResponse, esphome_api_DeviceInfoResponse, 2)


PB_BIND(esphome_api_ListEntitiesRequest, esphome_api_ListEntitiesRequest, AUTO)


PB_BIND(esphome_api_EntityInfo, esphome_api_EntityInfo, AUTO)


PB_BIND(esphome_api_ListEntitiesResponse, esphome_api_ListEntitiesResponse, 4)


PB_BIND(esphome_api_SubscribeStatesRequest, esphome_api_SubscribeStatesRequest, AUTO)


PB_BIND(esphome_api_BinarySensorStateResponse, esphome_api_BinarySensorStateResponse, AUTO)


PB_BIND(esphome_api_SwitchStateResponse, esphome_api_SwitchStateResponse, AUTO)


PB_BIND(esphome_api_SensorStateResponse, esphome_api_SensorStateResponse, AUTO)


PB_BIND(esphome_api_TextSensorStateResponse, esphome_api_TextSensorStateResponse, AUTO)


PB_BIND(esphome_api_SwitchCommandRequest, esphome_api_SwitchCommandRequest, AUTO)


PB_BIND(esphome_api_LightCommandRequest, esphome_api_LightCommandRequest, AUTO)


PB_BIND(esphome_api_PingRequest, esphome_api_PingRequest, AUTO)


PB_BIND(esphome_api_PingResponse, esphome_api_PingResponse, AUTO)


PB_BIND(esphome_api_DisconnectRequest, esphome_api_DisconnectRequest, AUTO)


PB_BIND(esphome_api_DisconnectResponse, esphome_api_DisconnectResponse, AUTO)


PB_BIND(esphome_api_SubscribeLogsRequest, esphome_api_SubscribeLogsRequest, AUTO)


PB_BIND(esphome_api_LogMessage, esphome_api_LogMessage, 2)


PB_BIND(esphome_api_Frame, esphome_api_Frame, 2)



